// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPFna0O0TQUrf5aBgzTe12fKsz9nWIrg',
    appId: '1:505698623774:ios:c7b237ccc332416aaae90f',
    messagingSenderId: '505698623774',
    projectId: 'nse-test-a9454',
    storageBucket: 'nse-test-a9454.appspot.com',
    androidClientId: '505698623774-1ar0h8p5mja1h85tnddjopfa5m097t9t.apps.googleusercontent.com',
    iosClientId: '505698623774-arhuujh7vrjoo0tmtetgpg0gpj9v24j1.apps.googleusercontent.com',
    iosBundleId: 'com.integro.testphoneauth.dev',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBknnHmAPKxml674kdacug35h0y9oiMK24',
    appId: '1:505698623774:android:1f52fcb0d6f09be3aae90f',
    messagingSenderId: '505698623774',
    projectId: 'nse-test-a9454',
    storageBucket: 'nse-test-a9454.appspot.com',
  );

}